version: '2'
services:
  crm-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/crm/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=crm
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
